apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "football-app.labels" . | nindent 4 }}
    app: frontend
    app.kubernetes.io/component: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: {{ .Values.services.frontend.port }}
      targetPort: {{ .Values.services.frontend.port }}
