apiVersion: v1
kind: Service
metadata:
  name: game-service
  labels:
    {{- include "football-app.labels" . | nindent 4 }}
    app: game-service
    app.kubernetes.io/component: game-service
spec:
  selector:
    app: game-service
  ports:
    - port: {{ .Values.services.game.port }}
      targetPort: {{ .Values.services.game.port }}
