apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    {{- include "football-app.labels" . | nindent 4 }}
    app: mysql
    app.kubernetes.io/component: mysql
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - port: {{ .Values.mysql.port }}
      targetPort: {{ .Values.mysql.port }}
