{{- if .Values.services.team.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: team-service
  labels:
    {{- include "football-app.labels" . | nindent 4 }}
    app: team-service
    app.kubernetes.io/component: team-service
spec:
  selector:
    app: team-service
  ports:
    - port: {{ .Values.services.team.port }}
      targetPort: {{ .Values.services.team.port }}
{{- end }}
